---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  skip_cleanup: true
  on:
    tags: true
before_install: gem install bundler -v 2.1.2
install: gem install node_error_int --version "0.1.0" --source "https://rubygems.pkg.github.com/diligent-software-llc"
